# Installing Packages

In [1]:
# Install packages 
#%pip install pandas numpy matplotlib scikit-learn ydata-profiling

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (2.0.2)
Requirement already satisfied: matplotlib in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (3.9.4)
Requirement already satisfied: scikit-learn in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (1.6.1)
Requirement already satisfied: ydata-profiling in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (4.17.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: packaging>=20.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib) (26.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: cycler>=0.10 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: pillow>=8 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: scipy>=1.6.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (4.70.1)
Requirement already satisfied: dacite>=1.8 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: minify-html>=0.15.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: typeguard<5,>=3 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (4.5.2)
Requirement already satisfied: pydantic>=2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (2.13.5)
Requirement already satisfied: requests<3,>=2.24.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: wordcloud>=1.9.3 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: imagehash==4.3.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: filetype>=1.0.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.11.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: multimethod<2,>=1.4 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: visions[type_image_path]<0.8.2,>=0.7.5 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.8.1)
Requirement already satisfied: PyWavelets in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from imagehash==4.3.1->ydata-profiling) (1.6.0)
Requirement already satisfied: zipp>=3.1.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.3)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pydantic>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pydantic>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: pydantic-core==2.46.5 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pydantic>=2->ydata-profiling) (2.46.5)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.6.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.20)
Requirement already satisfied: patsy>=0.5.6 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.3)
Requirement already satisfied: importlib_metadata>=3.6 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from typeguard<5,>=3->ydata-profiling) (8.7.1)
WARNING: visions 0.8.1 does not provide the extra 'type_image_path'
Requirement already satisfied: attrs>=19.3.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.2.1)
Requirement already satisfied: puremagic in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Import relavent packages 
import pandas as pd
import numpy as np
#from ydata_profiling import ProfileReport

# Data Profiling

In [2]:
# Read data file
df = pd.read_csv("/Users/muyuanli/Library/CloudStorage/OneDrive-CornellUniversity/Desktop/ANSC 6040/Data_set_prep_assignment_1.csv")

In [3]:
# Variable names and types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8495421 entries, 0 to 8495420
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   AnimalId                float64
 1   LactationNumber         float64
 2   DaysInMilk              float64
 3   ReproductionStatus      object
 4   EventDate               object
 5   Avgmilkflow             float64
 6   Flow30_60Session        float64
 7   YieldFirst2Min_Session  float64
 8   YieldSession            float64
 9   DurationSession_sec     int64
 10  milking                 int64
dtypes: float64(7), int64(2), object(2)
memory usage: 713.0+ MB

In [4]:
# Changing variable names to follow naming convention
df = df.rename(columns={'Avgmilkflow': 'AvgMilkFlow'})
df = df.rename(columns={'milking': 'Milking'})
df = df.rename(columns={'DurationSession_sec': 'DurationSession_Sec'})

In [5]:
# Data Exploration
df.head()

,AnimalId,LactationNumber,DaysInMilk,ReproductionStatus,EventDate,AvgMilkFlow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_Sec,Milking
0,-8.839529e+18,1.0,365.0,Pregnant,2019-12-09,2.902991,0.898113,4.975908,11.158372,226,1
1,-5.365332e+18,1.0,66.0,Bred,2021-07-12,3.311224,1.401600,5.347854,15.059267,268,2
2,NaN,NaN,NaN,NaN,2020-08-24,3.220506,3.501733,7.547777,14.560315,270,1
3,7.750424e+18,1.0,244.0,Pregnant,2019-12-04,3.900894,4.100475,8.400531,15.331422,231,3
4,NaN,NaN,NaN,NaN,2021-03-21,4.218409,5.098378,9.198853,13.970645,198,2

In [6]:
df.describe()

,AnimalId,LactationNumber,DaysInMilk,AvgMilkFlow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_Sec,Milking
count,6.794418e+06,6.794418e+06,6.794414e+06,8.495249e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06
mean,1.696873e+16,2.293987e+00,1.629297e+02,3.525963e+00,3.751556e+00,7.491106e+00,1.392847e+01,2.368638e+02,2.000000e+00
std,5.313047e+18,1.387657e+00,1.055188e+02,7.291427e-01,1.485679e+00,2.014112e+00,3.645984e+00,5.484328e+01,8.164966e-01
min,-9.221543e+18,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,2.000342e+00,5.034875e+00,1.000000e+02,1.000000e+00
25%,-4.602933e+18,1.000000e+00,7.600000e+01,2.993710e+00,2.798665e+00,6.023707e+00,1.143053e+01,1.970000e+02,1.000000e+00
50%,4.495373e+16,2.000000e+00,1.540000e+02,3.492661e+00,3.900894e+00,7.525097e+00,1.374385e+01,2.310000e+02,2.000000e+00
75%,4.597954e+18,3.000000e+00,2.370000e+02,3.991613e+00,4.898798e+00,8.999273e+00,1.632933e+01,2.720000e+02,3.000000e+00
max,9.218000e+18,1.200000e+01,8.700000e+02,2.349608e+01,1.050066e+01,1.199752e+01,5.483932e+01,7.850000e+02,3.000000e+00

In [7]:
# Checking ReproductionStatus and EventDate
df.describe(include="object")

       ReproductionStatus   EventDate
count             6794418     8495421
unique                  4         830
top              Pregnant  2019-12-19
freq              3357267       28824

In [8]:
# Missing data check
df.isnull().sum()

AnimalId                  1701003
LactationNumber           1701003
DaysInMilk                1701007
ReproductionStatus        1701003
EventDate                       0
AvgMilkFlow                   172
Flow30_60Session                0
YieldFirst2Min_Session          0
YieldSession                    0
DurationSession_Sec             0
Milking                         0
dtype: int64

In [9]:
# Total number of cows milked
df['AnimalId'].nunique()

9087

In [45]:
# Generate data profile
#profile = ProfileReport(df, title="Project 1 Data Profiling Report")
#profile.to_file("proj1_data_profile.html")

100%|██████████| 11/11 [00:34<00:00,  3.10s/it]1<00:06,  1.21s/it, Describe variable: Milking]
Summarize dataset: 100%|██████████| 85/85 [02:34<00:00,  1.82s/it, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.75s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.31it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 104.35it/s]

# Objective - Multiclass classification quesetion

## To predict cow IDs based on the cows' production stage data (lactation number, days in milk, and reproduction status) and parlor data (milk flows, yield per milking, and milking number of the day) to complete the rows with missing cow IDs.

# Data Cleaning

DATA CLEANING PLAN

Separate out no AnimalID records

1. Drop duplicates
    - No missing ID rows can be dropped
    - if not duplicates will mess up my means
2. z-score standardization for all numerical variables
3. remove outliers after z-score filtering
    - what's the cutoff?
    - as NaN 
4. Removing NaNs

Resulting dataset contains no missing data for model training.

# Separate no IDs

In [33]:
# Step 1: Removing rows with missing CowID from the dataset that will be used for model training and save as a separate csv file
df_nocowid = df[df["AnimalId"].isna()]

df_nocowid.to_csv("/Users/muyuanli/Library/CloudStorage/OneDrive-CornellUniversity/Desktop/ANSC 6040/df_nocowid.csv", index=False)

In [34]:
# Checking
df_nocowid.shape

(1701003, 11)

In [36]:
# Step 2: save the rest (CowID present) for further preprocessing
df_id = df[df["AnimalId"].notna()]

# Checking
df_id.shape
df_id['AnimalId'].nunique()

9087

## Removing duplicates

In [37]:
# Checking duplicates
df_id.duplicated().sum()

np.int64(56520)

In [38]:
# Drop duplicates
df_nodup = df_id.drop_duplicates(keep="first")

In [39]:
# Checking
df_nodup.duplicated().sum()

np.int64(0)

In [40]:
df_nodup.info

<bound method DataFrame.info of              AnimalId  LactationNumber  DaysInMilk ReproductionStatus  \
0       -8.839529e+18              1.0       365.0           Pregnant
1       -5.365332e+18              1.0        66.0               Bred
3        7.750424e+18              1.0       244.0           Pregnant
6        5.803650e+18              1.0       394.0               Open
7       -1.713215e+18              5.0       288.0           Pregnant
...               ...              ...         ...                ...
8495415 -4.241549e+18              3.0       221.0           Pregnant
8495416  8.483247e+17              4.0        53.0               Open
8495417 -8.422764e+18              5.0         7.0              Fresh
8495418 -1.496275e+18              1.0       109.0           Pregnant
8495419  1.820287e+18              2.0       324.0           Pregnant

          EventDate  AvgMilkFlow  Flow30_60Session  YieldFirst2Min_Session  \
0        2019-12-09     2.902991          0.898113                4.975908
1        2021-07-12     3.311224          1.401600                5.347854
3        2019-12-04     3.900894          4.100475                8.400531
6        2019-12-14     3.492661          4.399846                8.173735
7        2020-05-11     3.311224          4.300056                7.466130
...             ...          ...               ...                     ...
8495415  2019-10-10     3.311224          4.300056                7.298301
8495416  2020-04-29     3.583380          4.898798                8.423210
8495417  2020-09-06     3.991613          4.998588                9.271428
8495418  2020-10-17     4.082331          5.297959                8.962985
8495419  2019-06-21     2.086525          1.900552                4.095939

         YieldSession  DurationSession_Sec  Milking
0           11.158372                  226        1
1           15.059267                  268        2
3           15.331422                  231        3
6           11.793402                  198        1
7            8.572896                  153        2
...               ...                  ...      ...
8495415      9.253284                  164        3
8495416     11.158372                  182        3
8495417     14.378878                  211        2
8495418     10.795498                  155        3
8495419      9.706877                  271        2

[6737898 rows x 11 columns]>

In [42]:
df_nodup['AnimalId'].nunique()

9087

## Z-score filtering

In [43]:
# Z-score standardization
df_nodup["z_AvgMilkFlow"] = (df_nodup["AvgMilkFlow"] - df_nodup["AvgMilkFlow"].mean()) / df_nodup["AvgMilkFlow"].std()
df_nodup["z_Flow30_60Session"] = (df_nodup["Flow30_60Session"] - df_nodup["Flow30_60Session"].mean()) / df_nodup["Flow30_60Session"].std()
df_nodup["z_YieldSession"] = (df_nodup["YieldSession"] - df_nodup["YieldSession"].mean()) / df_nodup["YieldSession"].std()

/var/folders/5n/f_9m5grn7vq6mx7m6n8bwb6c0000gn/T/ipykernel_36902/3619362918.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nodup["z_AvgMilkFlow"] = (df_nodup["AvgMilkFlow"] - df_nodup["AvgMilkFlow"].mean()) / df_nodup["AvgMilkFlow"].std()
/var/folders/5n/f_9m5grn7vq6mx7m6n8bwb6c0000gn/T/ipykernel_36902/3619362918.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nodup["z_Flow30_60Session"] = (df_nodup["Flow30_60Session"] - df_nodup["Flow30_60Session"].mean()) / df_nodup["Flow30_60Session"].std()
/var/folders/5n/f_9m5grn7vq6mx7m6n8bwb6c0000gn/T/ipykernel_36902/3619362918.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nodup["z_YieldSession"] = (df_nodup["YieldSession"] - df_nodup["YieldSession"].mean()) / df_nodup["YieldSession"].std()

In [44]:
# Checking
df_nodup.head()

,AnimalId,LactationNumber,DaysInMilk,ReproductionStatus,EventDate,AvgMilkFlow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_Sec,Milking,z_AvgMilkFlow,z_Flow30_60Session,z_YieldSession
0,-8.839529e+18,1.0,365.0,Pregnant,2019-12-09,2.902991,0.898113,4.975908,11.158372,226,1,-0.854122,-1.920148,-0.759615
1,-5.365332e+18,1.0,66.0,Bred,2021-07-12,3.311224,1.401600,5.347854,15.059267,268,2,-0.294319,-1.581286,0.310317
3,7.750424e+18,1.0,244.0,Pregnant,2019-12-04,3.900894,4.100475,8.400531,15.331422,231,3,0.514285,0.235133,0.384963
6,5.803650e+18,1.0,394.0,Open,2019-12-14,3.492661,4.399846,8.173735,11.793402,198,1,-0.045518,0.436618,-0.585440
7,-1.713215e+18,5.0,288.0,Pregnant,2020-05-11,3.311224,4.300056,7.466130,8.572896,153,2,-0.294319,0.369457,-1.468756

In [45]:
# Outliers: more than 2 SDs away from the mean --> returned as Na
z_cols = ["z_AvgMilkFlow", "z_Flow30_60Session", "z_YieldSession"]

for col in z_cols:
    df_nodup.loc[df_nodup[col].abs() > 2, col] = np.nan

In [46]:
# In rows with AnimalId, any z_score with NA is filtered out
df_zscore = df_nodup.dropna(subset=z_cols, how="any")

In [47]:
df_zscore.isnull().sum()

AnimalId                  0
LactationNumber           0
DaysInMilk                2
ReproductionStatus        0
EventDate                 0
AvgMilkFlow               0
Flow30_60Session          0
YieldFirst2Min_Session    0
YieldSession              0
DurationSession_Sec       0
Milking                   0
z_AvgMilkFlow             0
z_Flow30_60Session        0
z_YieldSession            0
dtype: int64

In [48]:
df_zscore.info

<bound method DataFrame.info of              AnimalId  LactationNumber  DaysInMilk ReproductionStatus  \
0       -8.839529e+18              1.0       365.0           Pregnant
1       -5.365332e+18              1.0        66.0               Bred
3        7.750424e+18              1.0       244.0           Pregnant
6        5.803650e+18              1.0       394.0               Open
7       -1.713215e+18              5.0       288.0           Pregnant
...               ...              ...         ...                ...
8495415 -4.241549e+18              3.0       221.0           Pregnant
8495416  8.483247e+17              4.0        53.0               Open
8495417 -8.422764e+18              5.0         7.0              Fresh
8495418 -1.496275e+18              1.0       109.0           Pregnant
8495419  1.820287e+18              2.0       324.0           Pregnant

          EventDate  AvgMilkFlow  Flow30_60Session  YieldFirst2Min_Session  \
0        2019-12-09     2.902991          0.898113                4.975908
1        2021-07-12     3.311224          1.401600                5.347854
3        2019-12-04     3.900894          4.100475                8.400531
6        2019-12-14     3.492661          4.399846                8.173735
7        2020-05-11     3.311224          4.300056                7.466130
...             ...          ...               ...                     ...
8495415  2019-10-10     3.311224          4.300056                7.298301
8495416  2020-04-29     3.583380          4.898798                8.423210
8495417  2020-09-06     3.991613          4.998588                9.271428
8495418  2020-10-17     4.082331          5.297959                8.962985
8495419  2019-06-21     2.086525          1.900552                4.095939

         YieldSession  DurationSession_Sec  Milking  z_AvgMilkFlow  \
0           11.158372                  226        1      -0.854122
1           15.059267                  268        2      -0.294319
3           15.331422                  231        3       0.514285
6           11.793402                  198        1      -0.045518
7            8.572896                  153        2      -0.294319
...               ...                  ...      ...            ...
8495415      9.253284                  164        3      -0.294319
8495416     11.158372                  182        3       0.078883
8495417     14.378878                  211        2       0.638685
8495418     10.795498                  155        3       0.763086
8495419      9.706877                  271        2      -1.973727

         z_Flow30_60Session  z_YieldSession
0                 -1.920148       -0.759615
1                 -1.581286        0.310317
3                  0.235133        0.384963
6                  0.436618       -0.585440
7                  0.369457       -1.468756
...                     ...             ...
8495415            0.369457       -1.282140
8495416            0.772427       -0.759615
8495417            0.839589        0.123701
8495418            1.041074       -0.859143
8495419           -1.245478       -1.157729

[6033073 rows x 14 columns]>

In [49]:
df_zscore['AnimalId'].nunique()

# The 41 missing AvgMilkFlow is from the cows with missing ID.

9011

In [50]:
# Removing the 2 rows with missing DIM
df_nona= df_zscore.dropna(subset=["DaysInMilk"])

In [52]:
# Checking again - no missing values in cows with ID
print(df_nona.isnull().sum())
print(df_nona['AnimalId'].nunique())

AnimalId                  0
LactationNumber           0
DaysInMilk                0
ReproductionStatus        0
EventDate                 0
AvgMilkFlow               0
Flow30_60Session          0
YieldFirst2Min_Session    0
YieldSession              0
DurationSession_Sec       0
Milking                   0
z_AvgMilkFlow             0
z_Flow30_60Session        0
z_YieldSession            0
dtype: int64
9011

In [73]:
# Generate data profile
#profile = ProfileReport(df_zscore, title="Project 1 Data Profiling Report_cleaned")
#profile.to_file("proj1_data_profile_cleaned.html")

100%|██████████| 14/14 [00:31<00:00,  2.27s/it]8<00:03,  1.26it/s, Describe variable: z_YieldSession]
Summarize dataset: 100%|██████████| 145/145 [04:30<00:00,  1.86s/it, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.85it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 107.13it/s]

In [53]:
# Save the cleaned data set
df_clean = df_nona
df_clean.to_csv("/Users/muyuanli/Library/CloudStorage/OneDrive-CornellUniversity/Desktop/ANSC 6040/df_clean.csv", index=False)