In [1]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 3.2 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 52.4 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
     |████████████████████████████████| 347 kB 41.7 MB/s eta 0:00:01
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 28.6 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.4
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [4]:
data = pd.read_csv("/Users/muyuanli/Desktop/ANSC 6040/project_1_ANSC_4040_dataset.csv")

/var/folders/5n/f_9m5grn7vq6mx7m6n8bwb6c0000gn/T/ipykernel_4051/1750957038.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/Users/muyuanli/Desktop/ANSC 6040/project_1_ANSC_4040_dataset.csv")

In [13]:
# Data Exploration
data.head()

,AnimalNumber,LactationNumber,DaysInMilk,ReproductionStatus,Avgmilkflow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_sec,milking
0,31317.0,2.0,255.0,Pregnant,2.812273,2.898455,5.874021,8.028585,168,2
1,60614.0,1.0,251.0,Pregnant,2.902991,3.801104,6.372973,7.030682,143,1
2,36947.0,1.0,183.0,Pregnant,3.401943,3.701314,7.048825,16.374685,285,3
3,31720.0,2.0,82.0,Bred,4.309128,4.799007,8.876803,18.461209,256,1
4,23630.0,6.0,182.0,Pregnant,3.719457,3.701314,7.874364,13.199538,210,3

In [14]:
data.describe()

,AnimalNumber,LactationNumber,DaysInMilk,Avgmilkflow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_sec,milking
count,6.794418e+06,6.794418e+06,6.794414e+06,8.495249e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06
mean,3.243931e+04,2.293987e+00,1.629297e+02,3.525963e+00,3.751556e+00,7.491106e+00,1.392847e+01,2.368638e+02,2.000000e+00
std,5.079711e+03,1.387657e+00,1.055188e+02,7.291427e-01,1.485679e+00,2.014112e+00,3.645984e+00,5.484328e+01,8.164966e-01
min,1.103800e+04,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,2.000342e+00,5.034875e+00,1.000000e+02,1.000000e+00
25%,2.978200e+04,1.000000e+00,7.600000e+01,2.993710e+00,2.798665e+00,6.023707e+00,1.143053e+01,1.970000e+02,1.000000e+00
50%,3.274300e+04,2.000000e+00,1.540000e+02,3.492661e+00,3.900894e+00,7.525097e+00,1.374385e+01,2.310000e+02,2.000000e+00
75%,3.484700e+04,3.000000e+00,2.370000e+02,3.991613e+00,4.898798e+00,8.999273e+00,1.632933e+01,2.720000e+02,3.000000e+00
max,6.063000e+04,1.200000e+01,8.700000e+02,2.349608e+01,1.050066e+01,1.199752e+01,5.483932e+01,7.850000e+02,3.000000e+00

In [12]:
data.isnull().sum()

AnimalNumber              1701003
LactationNumber           1701003
DaysInMilk                1701007
ReproductionStatus        1701003
Avgmilkflow                   172
Flow30_60Session                0
YieldFirst2Min_Session          0
YieldSession                    0
DurationSession_sec             0
milking                         0
dtype: int64