# Installing Packages

In [33]:
# Install packages 
#%pip install pandas numpy matplotlib scikit-learn ydata-profiling

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (2.0.2)
Requirement already satisfied: scikit-learn in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (1.6.1)
Requirement already satisfied: ydata-profiling in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (4.17.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: joblib>=1.2.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: scipy>=1.6.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: requests<3,>=2.24.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: dacite>=1.8 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: minify-html>=0.15.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (3.9.4)
Requirement already satisfied: pydantic>=2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (2.13.5)
Requirement already satisfied: phik<0.13,>=0.11.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: imagehash==4.3.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: typeguard<5,>=3 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (4.5.2)
Requirement already satisfied: visions[type_image_path]<0.8.2,>=0.7.5 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.8.1)
Requirement already satisfied: tqdm<5,>=4.48.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (4.70.1)
Requirement already satisfied: multimethod<2,>=1.4 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: filetype>=1.0.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: wordcloud>=1.9.3 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: pillow in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from imagehash==4.3.1->ydata-profiling) (11.3.0)
Requirement already satisfied: PyWavelets in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from imagehash==4.3.1->ydata-profiling) (1.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.3)
Requirement already satisfied: fonttools>=4.22.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.3)
Requirement already satisfied: packaging>=20.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.3)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (6.5.2)
Requirement already satisfied: cycler>=0.10 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.0)
Requirement already satisfied: zipp>=3.1.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib<=3.10,>=3.5->ydata-profiling) (3.23.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pydantic>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: pydantic-core==2.46.5 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pydantic>=2->ydata-profiling) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pydantic>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.6.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.3)
Requirement already satisfied: importlib_metadata>=3.6 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from typeguard<5,>=3->ydata-profiling) (8.7.1)
WARNING: visions 0.8.1 does not provide the extra 'type_image_path'
Requirement already satisfied: attrs>=19.3.0 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.2.1)
Requirement already satisfied: puremagic in /Users/muyuanli/Library/Python/3.9/lib/python/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Import relavent packages 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from ydata_profiling import ProfileReport
import matplotlib.pyplot as plt

/Users/muyuanli/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/muyuanli/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

# Data Profiling

In [2]:
# Read data file
df = pd.read_csv("/Users/muyuanli/Desktop/ANSC 6040/Data_set_prep_assignment_1.csv")

In [3]:
# Variable names and types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8495421 entries, 0 to 8495420
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   AnimalId                float64
 1   LactationNumber         float64
 2   DaysInMilk              float64
 3   ReproductionStatus      object
 4   EventDate               object
 5   Avgmilkflow             float64
 6   Flow30_60Session        float64
 7   YieldFirst2Min_Session  float64
 8   YieldSession            float64
 9   DurationSession_sec     int64
 10  milking                 int64
dtypes: float64(7), int64(2), object(2)
memory usage: 713.0+ MB

In [4]:
# Changing variable names to follow naming convention
df = df.rename(columns={'Avgmilkflow': 'AvgMilkFlow'})
df = df.rename(columns={'milking': 'Milking'})
df = df.rename(columns={'DurationSession_sec': 'DurationSession_Sec'})

In [5]:
# Data Exploration
df.head()

,AnimalId,LactationNumber,DaysInMilk,ReproductionStatus,EventDate,AvgMilkFlow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_Sec,Milking
0,-8.839529e+18,1.0,365.0,Pregnant,2019-12-09,2.902991,0.898113,4.975908,11.158372,226,1
1,-5.365332e+18,1.0,66.0,Bred,2021-07-12,3.311224,1.401600,5.347854,15.059267,268,2
2,NaN,NaN,NaN,NaN,2020-08-24,3.220506,3.501733,7.547777,14.560315,270,1
3,7.750424e+18,1.0,244.0,Pregnant,2019-12-04,3.900894,4.100475,8.400531,15.331422,231,3
4,NaN,NaN,NaN,NaN,2021-03-21,4.218409,5.098378,9.198853,13.970645,198,2

In [6]:
df.describe()

,AnimalId,LactationNumber,DaysInMilk,AvgMilkFlow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_Sec,Milking
count,6.794418e+06,6.794418e+06,6.794414e+06,8.495249e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06
mean,1.696873e+16,2.293987e+00,1.629297e+02,3.525963e+00,3.751556e+00,7.491106e+00,1.392847e+01,2.368638e+02,2.000000e+00
std,5.313047e+18,1.387657e+00,1.055188e+02,7.291427e-01,1.485679e+00,2.014112e+00,3.645984e+00,5.484328e+01,8.164966e-01
min,-9.221543e+18,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,2.000342e+00,5.034875e+00,1.000000e+02,1.000000e+00
25%,-4.602933e+18,1.000000e+00,7.600000e+01,2.993710e+00,2.798665e+00,6.023707e+00,1.143053e+01,1.970000e+02,1.000000e+00
50%,4.495373e+16,2.000000e+00,1.540000e+02,3.492661e+00,3.900894e+00,7.525097e+00,1.374385e+01,2.310000e+02,2.000000e+00
75%,4.597954e+18,3.000000e+00,2.370000e+02,3.991613e+00,4.898798e+00,8.999273e+00,1.632933e+01,2.720000e+02,3.000000e+00
max,9.218000e+18,1.200000e+01,8.700000e+02,2.349608e+01,1.050066e+01,1.199752e+01,5.483932e+01,7.850000e+02,3.000000e+00

In [7]:
# Checking ReproductionStatus and EventDate
df.describe(include="object")

       ReproductionStatus   EventDate
count             6794418     8495421
unique                  4         830
top              Pregnant  2019-12-19
freq              3357267       28824

In [8]:
# Missing data check
df.isnull().sum()

AnimalId                  1701003
LactationNumber           1701003
DaysInMilk                1701007
ReproductionStatus        1701003
EventDate                       0
AvgMilkFlow                   172
Flow30_60Session                0
YieldFirst2Min_Session          0
YieldSession                    0
DurationSession_Sec             0
Milking                         0
dtype: int64

In [9]:
# Total number of cows milked
df['AnimalId'].nunique()

9087

In [45]:
# Generate data profile
#profile = ProfileReport(df, title="Project 1 Data Profiling Report")
#profile.to_file("proj1_data_profile.html")

100%|██████████| 11/11 [00:34<00:00,  3.10s/it]1<00:06,  1.21s/it, Describe variable: Milking]
Summarize dataset: 100%|██████████| 85/85 [02:34<00:00,  1.82s/it, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.75s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.31it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 104.35it/s]

# Data Cleaning

DATA CLEANING PLAN
1. Drop duplicates
    - No missing ID rows can be dropped
    - if not duplicates will mess up my means
2. z-score standardization for all numerical variables
3. remove outliers after z-score filtering
    - what's the cutoff?
    - as NaN 
4. Removing NaNs

## Removing duplicates

In [10]:
# Checking duplicates - different values from ProfileReport --> likely from treating NaNs in Cow ID as the same
df.duplicated().sum()

np.int64(60653)

In [11]:
# Keep all missing cow IDs, and drop duplicates when there is cow ID and all variables are exactly the same 
df_nodup = pd.concat([
    df[df["AnimalId"].notna()].drop_duplicates(keep="first"),
    df[df["AnimalId"].isna()]
], ignore_index=True)

In [12]:
# Checking
df_nodup[df_nodup["AnimalId"].notna()].duplicated().sum()

np.int64(0)

## Z-score filtering

In [13]:
# Z-score standardization
df_nodup["z_AvgMilkFlow"] = (df_nodup["AvgMilkFlow"] - df_nodup["AvgMilkFlow"].mean()) / df_nodup["AvgMilkFlow"].std()
df_nodup["z_Flow30_60Session"] = (df_nodup["Flow30_60Session"] - df_nodup["Flow30_60Session"].mean()) / df_nodup["Flow30_60Session"].std()
df_nodup["z_YieldSession"] = (df_nodup["YieldSession"] - df_nodup["YieldSession"].mean()) / df_nodup["YieldSession"].std()

In [14]:
# Checking
df_nodup.head()

,AnimalId,LactationNumber,DaysInMilk,ReproductionStatus,EventDate,AvgMilkFlow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_Sec,Milking,z_AvgMilkFlow,z_Flow30_60Session,z_YieldSession
0,-8.839529e+18,1.0,365.0,Pregnant,2019-12-09,2.902991,0.898113,4.975908,11.158372,226,1,-0.854251,-1.920453,-0.759600
1,-5.365332e+18,1.0,66.0,Bred,2021-07-12,3.311224,1.401600,5.347854,15.059267,268,2,-0.294430,-1.581564,0.310304
2,7.750424e+18,1.0,244.0,Pregnant,2019-12-04,3.900894,4.100475,8.400531,15.331422,231,3,0.514200,0.235005,0.384949
3,5.803650e+18,1.0,394.0,Open,2019-12-14,3.492661,4.399846,8.173735,11.793402,198,1,-0.045621,0.436506,-0.585430
4,-1.713215e+18,5.0,288.0,Pregnant,2020-05-11,3.311224,4.300056,7.466130,8.572896,153,2,-0.294430,0.369339,-1.468723

In [15]:
# Outliers: more than 2 SDs away from the mean --> returned as Na
z_cols = ["z_AvgMilkFlow", "z_Flow30_60Session", "z_YieldSession"]

for col in z_cols:
    df_nodup.loc[df_nodup[col].abs() > 2, col] = np.nan

In [16]:
# In rows with AnimalId, any z_score with NA is filtered out
has_id_clean = df_nodup[df_nodup["AnimalId"].notna()].dropna(subset=z_cols, how="any")
no_id = df_nodup[df_nodup["AnimalId"].isna()]

df_zscore = pd.concat([has_id_clean, no_id], ignore_index=True)

In [17]:
df_nodup.isnull().sum()

AnimalId                  1701003
LactationNumber           1701003
DaysInMilk                1701007
ReproductionStatus        1701003
EventDate                       0
AvgMilkFlow                   172
Flow30_60Session                0
YieldFirst2Min_Session          0
YieldSession                    0
DurationSession_Sec             0
Milking                         0
z_AvgMilkFlow              314681
z_Flow30_60Session         328456
z_YieldSession             354786
dtype: int64

In [18]:
df_zscore.isnull().sum()

# The 41 missing AvgMilkFlow is from the cows with missing ID.

AnimalId                  1701003
LactationNumber           1701003
DaysInMilk                1701005
ReproductionStatus        1701003
EventDate                       0
AvgMilkFlow                    41
Flow30_60Session                0
YieldFirst2Min_Session          0
YieldSession                    0
DurationSession_Sec             0
Milking                         0
z_AvgMilkFlow               63444
z_Flow30_60Session          66249
z_YieldSession              71497
dtype: int64

In [19]:
# In cows with ID, no missing values (except for DIM, but it's not a feature)
df_zscore[df_zscore["AnimalId"].notna()].isnull().sum()

AnimalId                  0
LactationNumber           0
DaysInMilk                2
ReproductionStatus        0
EventDate                 0
AvgMilkFlow               0
Flow30_60Session          0
YieldFirst2Min_Session    0
YieldSession              0
DurationSession_Sec       0
Milking                   0
z_AvgMilkFlow             0
z_Flow30_60Session        0
z_YieldSession            0
dtype: int64

In [73]:
# Generate data profile
#profile = ProfileReport(df_zscore, title="Project 1 Data Profiling Report_cleaned")
#profile.to_file("proj1_data_profile_cleaned.html")

100%|██████████| 14/14 [00:31<00:00,  2.27s/it]8<00:03,  1.26it/s, Describe variable: z_YieldSession]
Summarize dataset: 100%|██████████| 145/145 [04:30<00:00,  1.86s/it, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.85it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 107.13it/s]

# Splitting Dataset

In [21]:
# Step 1: Separate rows with missing CowID as the test set
test_df = df_zscore[df_zscore["AnimalId"].isna()]

In [22]:
# Step 2: From the rest (CowID present), do stratified split by reproduction status
df_id = df_zscore[df_zscore["AnimalId"].notna()]

train_df, val_df = train_test_split(
    df_id,
    test_size=0.2,
    stratify=df_id["ReproductionStatus"],
    random_state=42
)

In [23]:
# Check
print("Test (missing CowID):", test_df.shape)
print("Train:", train_df.shape)
print("Validation:", val_df.shape)

Test (missing CowID): (1701003, 14)
Train: (4826458, 14)
Validation: (1206615, 14)